# see https://hub.docker.com/r/hypernode/deploy/tags for all possible tags
# pin the image to a specific version to stay in control with updates 
image: hypernode/deploy:alpha

stages:
    - build
    - deploy

build:
    stage: build
    only:
        - test
        - master
    script:
        - hypernode-deploy build
    artifacts:
        paths:
            - build/**

# Deploy to test configuration
# If you are only deploying to production remove this configuration
deploy_test:
    stage: deploy
    only:
        - test
    script:
        - hypernode-deploy deploy test -vvv

# Deploy to production
deploy_production:
    stage: deploy
    only:
        - master
    script:
        - hypernode-deploy deploy production
