# See https://quay.io/repository/hypernode/deploy?tab=tags for all possible tags.
image: quay.io/hypernode/deploy:3-php8.2-node18

stages:
    - build
    - deploy

build:
    stage: build
    only:
        - test
        - master
    script:
        - hypernode-deploy build
    artifacts:
        paths:
            - build/**

# Deploy to test configuration
# If you are only deploying to production remove this configuration
deploy_test:
    stage: deploy
    only:
        - test
    script:
        - hypernode-deploy deploy test -vvv
    after_script:
        - hypernode-deploy cleanup

# Deploy to production
deploy_production:
    stage: deploy
    only:
        - master
    script:
        - hypernode-deploy deploy production
