# See https://quay.io/repository/hypernode/deploy?tab=tags for all possible tags.
image: quay.io/hypernode/deploy:3-php8.2-node18

pipelines:
  branches:
    # Deploy to test configuration
    # If you are only deploying to production remove this configuration
    test:
      - step:
          name: build
          script:
            - hypernode-deploy build -vvv
          artifacts:
            - build/**
      - step:
          name: deploy
          deployment: test
          script:
            - hypernode-deploy deploy test -vvv
          after-script:
            - hypernode-deploy cleanup

    # Deploy to production
    master:
      - step:
          name: build
          script:
            - hypernode-deploy build
          artifacts:
            - build/**
      - step:
          name: deploy
          deployment: production
          script:
            - hypernode-deploy deploy production
